# Generated by Django 2.2.12 on 2020-04-27 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('items_in_order', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=500)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 4, 27, 20, 25, 0, 110392))),
                ('delivery_boy_id', models.CharField(default='not_assigned', max_length=200)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
