# Generated by Django 3.0.5 on 2020-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delivery_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='restaurant_logo/')),
            ],
        ),
    ]
