# Generated by Django 3.0.5 on 2020-04-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_person',
            name='rating',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=2),
        ),
    ]
