# Generated by Django 3.0.5 on 2020-05-02 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('restaurant_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('Main Courses', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50)),
                ('serviceable', models.CharField(choices=[('available', 'service available'), ('not available', 'service not available')], default='service available', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('veg', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='veg', max_length=30)),
                ('cuisine_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=500)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 5, 2, 12, 33, 43, 364950))),
                ('delivery_boy_id', models.CharField(default='not_assigned', max_length=200)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='food.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('res_id', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodItem')),
            ],
        ),
    ]
