# Generated by Django 3.0.5 on 2020-05-16 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('res_id', models.CharField(max_length=100)),
                ('food_id', models.CharField(max_length=100)),
                ('food_name', models.CharField(default='No Name', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Order Picked', 'Order Picked'), ('Delivery Boy Assigned', 'Delivery Boy Assigned'), ('Placed', 'Placed'), ('Processing', 'Processing'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=500)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2020, 5, 16, 15, 51, 53, 307742))),
                ('delivery_boy_id', models.CharField(default='not_assigned', max_length=200)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200)),
                ('item_name', models.CharField(default='Food', max_length=200)),
                ('quantity', models.IntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='food.Order')),
            ],
        ),
    ]
