# Generated by Django 3.0.5 on 2020-05-08 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200506_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditems',
            name='item_name',
            field=models.CharField(default='Food', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 21, 54, 28, 928976)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Order Picked', 'Order Picked'), ('Delivery Boy Assigned', 'Delivery Boy Assigned'), ('Placed', 'Placed'), ('Processing', 'Processing'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=500),
        ),
    ]
