# Generated by Django 3.0.5 on 2020-05-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200508_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food_name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 12, 13, 24, 551910)),
        ),
    ]
