# Generated by Django 3.0.5 on 2020-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('restaurant_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('veg', models.BooleanField(default=True)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('serviceable', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
