# Generated by Django 3.0.5 on 2020-04-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0003_auto_20200426_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='num_customers',
        ),
    ]
