# Generated by Django 3.0.5 on 2020-04-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0004_remove_fooditem_num_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
