# Generated by Django 3.0.5 on 2020-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0006_auto_20200429_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
