# Generated by Django 3.0.5 on 2020-04-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0007_auto_20200429_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='rating',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='serviceable',
            field=models.CharField(choices=[('available', 'service available'), ('not available', 'service not available')], default='service available', max_length=30),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='veg',
            field=models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='veg', max_length=30),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(max_length=300)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooditems.FoodItem')),
            ],
        ),
    ]
