# Generated by Django 3.0.5 on 2020-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0008_auto_20200430_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main Courses', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviews',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='veg',
            field=models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='veg', max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
