# Generated by Django 3.0.5 on 2020-05-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0009_auto_20200503_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('cuisines', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('avg_cost_for_a_person', models.IntegerField()),
                ('is_delivering_now', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooditems.Restaurant'),
        ),
    ]
