# Generated by Django 3.0.5 on 2020-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0010_auto_20200504_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant_id',
            field=models.CharField(max_length=100),
        ),
    ]
