# Generated by Django 3.0.5 on 2020-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0011_auto_20200504_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant_id',
            field=models.IntegerField(),
        ),
    ]
