# Generated by Django 3.0.5 on 2020-04-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=100)),
                ('startTime', models.TimeField()),
                ('closeTime', models.TimeField()),
                ('cuisine', models.CharField(max_length=20)),
                ('pricePerHead', models.IntegerField()),
                ('contactNumber', models.CharField(max_length=10)),
                ('review', models.CharField(editable=False, max_length=20)),
                ('username', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(editable=False, max_length=20)),
                ('vehicleNumber', models.CharField(editable=False, max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('drivingLicense', models.CharField(editable=False, max_length=13)),
                ('username', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('username', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
