# Generated by Django 3.0.5 on 2020-05-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('restaurant_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('Starters', 'Starters'), ('Main Courses', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50, null=True)),
                ('serviceable', models.CharField(choices=[('available', 'service available'), ('not available', 'service not available')], default='service available', max_length=30)),
                ('veg', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='veg', max_length=100)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('cuisines', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('avg_cost_for_a_person', models.IntegerField()),
                ('is_delivering_now', models.BooleanField(default=True)),
                ('restaurant_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=1, max_length=100)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('reviews', models.TextField(max_length=400, null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItems.FoodItem')),
            ],
        ),
    ]
