# Generated by Django 3.0.5 on 2020-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('cuisines', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField(max_length=11)),
                ('avg_cost_for_a_person', models.IntegerField(max_length=10)),
                ('is_delivering_now', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
