# Generated by Django 3.0.5 on 2020-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_cost_for_a_person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
