# Generated by Django 3.0.5 on 2020-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Order Picked', 'Order Picked'), ('Delivery Boy Assigned', 'Delivery Boy Assigned'), ('Placed', 'Placed'), ('Processing', 'Processing'), ('In Delivery', 'In Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=500)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy_id', models.CharField(default='not_assigned', max_length=200)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
